# Generated by Django 2.1.12 on 2019-10-15 04:55

from django.db import migrations, models


from django.db import migrations
from django.contrib.auth.admin import User


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'Admin'
    superuser.email = 'admin@admin.net'
    superuser.set_password('admin123')
    superuser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dataproviderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
		migrations.RunPython(create_superuser)
    ]
